apiVersion: v1
kind: Pod
metadata:
  name: init-demo1
spec:
  containers:
  - name: nginx
    image: nginx
  initContainers:
  - name: install
    image: busybox
    command:
    - sleep
    - "3600"
